### PR TITLE
created a contact form

### PR DESCRIPTION
**Pull request by Onyinye101**
This form allows users on the site to submit messages.

### CODE REVIEW

**Comment by taiwo-ladipo** [comment]
Well done @Onyinye101,
These form fields do not match what was requested for the news submission form.
Please refer to the question for the required fields on this page

**Comment by ToluEnny24** [comment]
Well done Onyinye. These are the required fields:
Title input field
News body field
An image upload button (for the news featured image)
A submit button (to post the news)

**Comment by ToluEnny24** [comment]
Well done Onyinye, i can see you have effected the changes

**Review by bilkisutace — APPROVED** [review]
Great job, well done!

**Pull request merged**
